const produtos = [
    {
        "id": 1,
        "titulo": "TV Samsung 50 polegadas",
        "descricao": "Smart TV 50 polegadas Crystal UHD 4K UN50AU8000GXZD. Sem detalhes",
        "valor": 1000.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["01-tv-samsung-50-polegadas-1.jpeg", "01-tv-samsung-50-polegadas-2.jpeg", "01-tv-samsung-50-polegadas-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Taci",
        "entregue": true,
        "pago": true
    },
    {
        "id": 2,
        "titulo": "Closet",
        "descricao": "Closet 3 Gavetas 7 Nichos 2 Cabideiros 1 Maleiro 236x159x54cm Legno Crema Prime Luciane",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["02-closet-1.jpeg", "02-closet-2.jpeg", "02-closet-3.jpeg", "02-closet-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 3,
        "titulo": "Closet",
        "descricao": "Closet 3 Gavetas 7 Nichos 2 Cabideiros 1 Maleiro 236x159x54cm Legno Crema Prime Luciane. Esse tem um detalhe, mostrado na imagem",
        "valor": 900.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["03-closet-1.jpeg", "03-closet-2.jpeg", "03-closet-3.jpeg", "03-closet-4.jpeg", "03-closet-5.jpeg", "03-closet-6.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 4,
        "titulo": "Gaveteiro Branco",
        "descricao": "Gaveteiro de Chão 66x45x45cm Madeira Branco Neve Luciane com 3 gavetas",
        "valor": 100.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["04-gaveteiro-branco-1.jpeg", "04-gaveteiro-branco-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 5,
        "titulo": "Gaveteiro Marrom",
        "descricao": "Gaveteiro de Chão 3 Gavetas 66x45x45cm Nogueira Dourado Luciane com 3 gavetas",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["05-gaveteiro-marrom-1.jpg", "05-gaveteiro-marrom-.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 6,
        "titulo": "Poltrona reclinável",
        "descricao": "Poltrona Reclinável de couro Ecológico, reclina encosto e pés. Marrom Norfolk",
        "valor": 1500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["06-poltrona-reclinavel-1.jpeg", "06-poltrona-reclinavel-2.jpeg", "06-poltrona-reclinavel-3.jpeg", "06-poltrona-reclinavel-4.jpeg", "06-poltrona-reclinavel-5.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 7,
        "titulo": "Microondas Branco",
        "descricao": "Micro-ondas Electrolux 20L Branco com Função Tira Odor e Descongelar",
        "valor": 250.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["07-microondas-1.jpeg", "07-microondas-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Harley",
        "entregue": true,
        "pago": true
    },
    {
        "id": 8,
        "titulo": "Máquina de Café Tres Corações + Capsulas",
        "descricao": "Máquina de Café Tres Corações + cerca de 100 capsulas diversas",
        "valor": 200.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["08-maquina-cafe-3-coracoes-1.webp", "08-maquina-cafe-3-coracoes-2.webp", "08-maquina-cafe-3-coracoes-3.webp"],
        "precoCerto": true,
        "reservadoPara": "Harley",
        "entregue": true,
        "pago": true
    },
    {
        "id": 9,
        "titulo": "PlayStation 4 + 2 jogos + 2 controles",
        "descricao": "PlayStation 4 + 2 jogos + 2 controles. Jogos: Fallout 4, Uncharted 4: A Thief's End. Controles: 2 originais.",
        "valor": 2000.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["09-playstation-4-1.jpeg", "09-playstation-4-2.jpeg", "09-playstation-4-3.jpeg", "61-1-fallout-4-1.png", "61-13-uncharted-4-a-thiefs-end-1.png"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 10,
        "titulo": "PlayStation 3 Slim + 5 jogos",
        "descricao": "PlayStation 3 Slim 320GB + 5 jogos originais + 1 controle original. Jogos: The Orange Box, Heavy Rain, Beyond: Two Souls, The Last of us, God of War Collection (1 e 2).",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["10-ps3-1.jpeg", "10-ps3-2.jpeg", "10-ps3-3.jpeg", "10-ps3-4.jpeg", "10-ps3-5.jpeg", "10-ps3-6.jpeg", "10-ps3-7.jpeg", "10-ps3-8.jpeg", "10-ps3-9.jpeg", "10-ps3-10.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 11,
        "titulo": "Nintendo Wii",
        "descricao": "Nintendo Wii preto desbloqueado + Wii Sports",
        "valor": 700.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["11-nintendo-wii-1.jpeg", "11-nintendo-wii-2.jpeg", "11-nintendo-wii-3.jpeg", "11-nintendo-wii-4.jpeg", "11-nintendo-wii-5.jpeg", "11-nintendo-wii-6.jpeg", "11-nintendo-wii-7.jpeg", "11-nintendo-wii-8.jpeg", "11-nintendo-wii-9.jpeg", "11-nintendo-wii-10.jpeg", "11-nintendo-wii-11.jpeg", "11-nintendo-wii-12.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 12,
        "titulo": "Super Nintendo Fat original",
        "descricao": "Super Nintendo Fat original + 2 controles originais. Sem jogos. Sem fonte.",
        "valor": 300.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["12-super-nintendo-1.jpeg", "12-super-nintendo-2.jpeg", "12-super-nintendo-3.jpeg", "12-super-nintendo-4.jpeg", "12-super-nintendo-5.jpeg", "12-super-nintendo-6.jpeg", "12-super-nintendo-7.jpeg", "12-super-nintendo-8.jpeg", "12-super-nintendo-9.jpeg", "12-super-nintendo-10.jpeg", "12-super-nintendo-11.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Marcelo Gorski",
        "entregue": true,
        "pago": true
    },
    {
        "id": 13,
        "titulo": "Máquina de Cortar Madeira",
        "descricao": "Máquina de Cortar Madeira",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Ferramentas",
        "imagens": ["13-maquina-cortar-madeira-1.webp"],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 14,
        "titulo": "Bicicleta Montain Bike",
        "descricao": "Bicicleta Montain Bike",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Transporte",
        "imagens": ["14-bike-montain-bike-1.jpeg", "14-bike-montain-bike-2.jpeg", "14-bike-montain-bike-3.jpeg", "14-bike-montain-bike-4.jpeg", "14-bike-montain-bike-5.jpeg", "14-bike-montain-bike-6.jpeg", "14-bike-montain-bike-7.jpeg"],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 15,
        "titulo": "Bicicleta Speed Cinza",
        "descricao": "Bicicleta Speed Cinza",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Transporte",
        "imagens": ["15-bike-speed-1.jpeg", "15-bike-speed-2.jpeg", "15-bike-speed-3.jpeg", "15-bike-speed-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 16,
        "titulo": "Longboard",
        "descricao": "Longboard",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Transporte",
        "imagens": ["16-longboard-1.jpeg", "16-longboard-2.jpeg", "16-longboard-3.jpeg", "16-longboard-4.jpeg", "16-longboard-5.jpeg", "16-longboard-6.jpeg", "16-longboard-7.jpeg", "16-longboard-8.jpeg"],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 17,
        "titulo": "Ferramentas",
        "descricao": "Ferramentas",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Ferramentas",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 18,
        "titulo": "Arco e Flecha",
        "descricao": "Arco e Flecha",
        "valor": 1200.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Armas",
        "imagens": ["18-arco-flecha-1.jpeg", "18-arco-flecha-2.jpeg", "18-arco-flecha-3.jpeg", "18-arco-flecha-4.jpeg", "18-arco-flecha-5.jpeg", "18-arco-flecha-6.jpeg", "18-arco-flecha-7.jpeg"],
        "precoCerto": false,
        "reservadoPara": "Marcelo Gorski",
        "entregue": true,
        "pago": true
    },
    {
        "id": 19,
        "titulo": "Crossbow",
        "descricao": "Crossbow",
        "valor": 50.00,
        "disponivel": false,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Armas",
        "imagens": ["19-crossbow-1.jpeg", "19-crossbow-2.jpeg", "19-crossbow-3.jpeg", "19-crossbow-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Marcelo Gorski",
        "entregue": true,
        "pago": true
    },
    {
        "id": 20,
        "titulo": "Armas Airsoft",
        "descricao": "Armas Airsoft",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 5,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Armas",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": true, // fake para definir os valores
        "pago": false
    },
    {
        "id": 21,
        "titulo": "Estante Nichos",
        "descricao": "Estante Nichos",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 22,
        "titulo": "Aquecedor à óleo - Mondial",
        "descricao": "Aquecedor à óleo",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 23,
        "titulo": "Câmera Digital",
        "descricao": "Câmera Digital",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 24,
        "titulo": "Mesa Escritório Madeira",
        "descricao": "Mesa Escritório Madeira",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 25,
        "titulo": "Mesa Escritório Branca",
        "descricao": "Mesa Escritório Branca",
        "valor": 200.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Juliana",
        "entregue": false,
        "pago": false
    },
    {
        "id": 26,
        "titulo": "Mesa Regulagem de Altura",
        "descricao": "Mesa Gamer Acegeek Venus C Regulagem De Altura 1 Motor 140cm. Pouco usada.",
        "valor": 1300.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Semi-nova",
        "categoria": "Móveis",
        "imagens": ["26-mesa-regulagem-de-altura-1.webp", "26-mesa-regulagem-de-altura-2.webp", "26-mesa-regulagem-de-altura-3.webp"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 27,
        "titulo": "Mesa de Jantar",
        "descricao": "Mesa de Jantar com tampo em vidro, 6 cadeiras",
        "valor": 2000.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["27-mesa-jantar-1.jpg", "27-mesa-jantar-2.jpg", "27-mesa-jantar-3.jpeg", "27-mesa-jantar-4.jpg", "27-mesa-jantar-5.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 28,
        "titulo": "Sofá",
        "descricao": "Sofá em L, 5 Lugares com um pufe. Esse valor é sem limpeza, do jeito que está.",
        "valor": 2200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 29,
        "titulo": "Rack Sala",
        "descricao": "Rack Sala",
        "valor": 500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["29-rack-sala-1.jpeg", "29-rack-sala-2.jpeg", "29-rack-sala-3.jpeg", "29-rack-sala-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 30,
        "titulo": "Cama de Solteiro",
        "descricao": "Cama de Solteiro baú com colchão e cabeceira",
        "valor": 700.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 31,
        "titulo": "Cama King Size",
        "descricao": "Cama King Size baú com colchão e cabeceira",
        "valor": 1800.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["31-cama-king-1.jpeg", "31-cama-king-2.jpeg", "31-cama-king-3.jpeg", "31-cama-king-4.jpeg", "31-cama-king-5.jpeg", "31-cama-king-6.jpeg", "31-cama-king-7.jpeg", "31-cama-king-8.jpeg", "31-cama-king-9.jpeg", "31-cama-king-10.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 32,
        "titulo": "TV Samsung The Frame",
        "descricao": "TV Samsung The Frame 4K 55 polegadas",
        "valor": 2300.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["32-tv-the-frame-1.jpeg", "32-tv-the-frame-2.jpeg", "32-tv-the-frame-3.jpeg", "32-tv-the-frame-4.jpeg", "32-tv-the-frame-5.jpeg", "32-tv-the-frame-6.jpeg", "32-tv-the-frame-7.jpeg", "32-tv-the-frame-8.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Sthu",
        "entregue": false,
        "pago": false
    },
    {
        "id": 33,
        "titulo": "Rede Wi-Fi Deco",
        "descricao": "Rede Wi-Fi Deco TP-Link.",
        "valor": 300.00,
        "disponivel": false,
        "quantidade": 2,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["33-rede-wi-fi-deco-1.jpeg", "33-rede-wi-fi-deco-2.jpeg", "33-rede-wi-fi-deco-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Cíntia",
        "entregue": false,
        "pago": false
    },
    {
        "id": 34,
        "titulo": "DVR com 4 cameras Infra VHD 3230b Full HD G4",
        "descricao": "DVR (MHDX 1104) com 4 cameras Infra VHD 3230b Full HD G4 Intelbras, HD, rolo de fio com cerca de 25 metros, conectores e fonte 12v",
        "valor": 1200.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 35,
        "titulo": "Rolo de fio CAT6",
        "descricao": "Rolo de fio CAT6",
        "valor": 1500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 36,
        "titulo": "Computador Gamer",
        "descricao": "Computador Gamer",
        "valor": 1500.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Keith",
        "entregue": true,
        "pago": true
    },
    {
        "id": 37,
        "titulo": "Luminária",
        "descricao": "Luminária",
        "valor": 150.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Sthu",
        "entregue": false,
        "pago": false
    },
    {
        "id": 38,
        "titulo": "Alexa + 2 lampadas inteligentes",
        "descricao": "1 Alexas + 2 lampadas inteligentes",
        "valor": 300.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Stan",
        "entregue": false,
        "pago": false
    },
    {
        "id": 39,
        "titulo": "Impressora L3250",
        "descricao": "Impressora",
        "valor": 500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 40,
        "titulo": "Massageador",
        "descricao": "Massageador",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 41,
        "titulo": "Cadeira Gamer Corsair",
        "descricao": "Cadeira Gamer Corsair",
        "valor": 1500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 42,
        "titulo": "Cadeira Escritório",
        "descricao": "Cadeira Escritório",
        "valor": 1500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 43,
        "titulo": "Geladeira",
        "descricao": "Geladeira",
        "valor": 1500.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Silvia",
        "entregue": false,
        "pago": false
    },
    {
        "id": 44,
        "titulo": "Fogão de Embutir 4 Bocas Preto com Mesa de Vidro Dako Supreme Bivolt",
        "descricao": "Fogão de Embutir 4 Bocas Preto com Mesa de Vidro Dako Supreme Bivolt",
        "valor": 750.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 45,
        "titulo": "Microondas",
        "descricao": "Microondas",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 46,
        "titulo": "Air Fryer",
        "descricao": "Air Fryer",
        "valor": 150.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Silvia",
        "entregue": false,
        "pago": false
    },
    {
        "id": 47,
        "titulo": "Ar Condicionado Portatil 12.000 Btus Frio Olympia Branco 127v",
        "descricao": "Ar Condicionado Portatil 12.000 Btus Frio Olympia Branco 127v",
        "valor": 2000.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["47-ar-condicionado-portátil-12000-btu-1.jpeg", "47-ar-condicionado-portátil-12000-btu-2.jpeg", "47-ar-condicionado-portátil-12000-btu-3.jpeg", "47-ar-condicionado-portátil-12000-btu-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 48,
        "titulo": "Ar Condicionado Portatil 12.000 Btus Frio Olympia Branco 127v",
        "descricao": "Ar Condicionado Portatil 12.000 Btus Frio Olympia Branco 127v",
        "valor": 2000.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["47-ar-condicionado-portátil-12000-btu-1.jpeg", "47-ar-condicionado-portátil-12000-btu-2.jpeg", "47-ar-condicionado-portátil-12000-btu-3.jpeg", "47-ar-condicionado-portátil-12000-btu-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 49,
        "titulo": "Ar Condicionado portátil 10000 BTU - 127v",
        "descricao": "Ar Condicionado portátil 10000 BTU Equation - 127v",
        "valor": 1500.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["49-ar-condicionado-portátil-10000-btu-1.jpeg", "49-ar-condicionado-portátil-10000-btu-2.jpeg", "49-ar-condicionado-portátil-10000-btu-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Harley",
        "entregue": true,
        "pago": true
    },
    {
        "id": 50,
        "titulo": "Ar Condicionado portátil 10000 BTU - 127v",
        "descricao": "Ar Condicionado portátil 10000 BTU Equation - 127v",
        "valor": 1500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["49-ar-condicionado-portátil-10000-btu-1.jpeg", "49-ar-condicionado-portátil-10000-btu-2.jpeg", "49-ar-condicionado-portátil-10000-btu-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 51,
        "titulo": "Pressurizador Komeco TP-820 - Bivolt",
        "descricao": "Pressurizador Komeco TP-820 - Bivolt - Configurado para 127v, 220v deve ser alterado o esquema de ligação",
        "valor": 600.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["51-pressurizador-1.jpeg", "51-pressurizador-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Cíntia",
        "entregue": false,
        "pago": false
    },
    {
        "id": 52,
        "titulo": "Aquecedor de água a gás glp lorenzetti branco lz 2000de glp bivolt",
        "descricao": "Aquecedor de água a gás glp lorenzetti branco lz 2000de glp bivolt - vai ser entregue revisado",
        "valor": 1400.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["52-aquecedor-de-água-de-passagem-à-gás-1.jpeg", "52-aquecedor-de-água-de-passagem-à-gás-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Maju",
        "entregue": false,
        "pago": false
    },
    {
        "id": 53,
        "titulo": "Botijão 13kg",
        "descricao": "Botijão 13kg",
        "valor": 80.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Ricardo Górski",
        "entregue": true,
        "pago": true
    },
    {
        "id": 54,
        "titulo": "Roteador ER605 Omada Gigabit Multi-WAN VPN Router",
        "descricao": "Roteador ER605 Omada Gigabit Multi-WAN VPN Router",
        "valor": 250.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 55,
        "titulo": "Aspirador de pó profissional",
        "descricao": "Aspirador de pó profissional",
        "valor": 750.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 56,
        "titulo": "Air Relax Sistema de recuperação de pernas PLUS + Botas",
        "descricao": "Bota de relaxamento das pernas - Air Relax Sistema de recuperação de pernas PLUS + Botas",
        "valor": 4500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["56-bota-de-relaxamento-das-pernas-1.jpeg", "56-bota-de-relaxamento-das-pernas-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 57,
        "titulo": "Quadro",
        "descricao": "Quadro",
        "valor": 150.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["57-quadro-1.jpeg", "57-quadro-2.jpeg", "57-quadro-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Marcelo Gorski",
        "entregue": true,
        "pago": true
    },
    {
        "id": 58,
        "titulo": "Máquina Lava e Seca Samsung",
        "descricao": "Máquina de lavar roupa Samsung, Lava e Seca, 10kg/6KG",
        "valor": 1700.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["58-maquina-de-lavar-roupa-1.jpeg", "58-maquina-de-lavar-roupa-2.jpeg", "58-maquina-de-lavar-roupa-3.jpeg", "58-maquina-de-lavar-roupa-4.jpeg", "58-maquina-de-lavar-roupa-5.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Stan",
        "entregue": false,
        "pago": false
    },
    {
        "id": 59,
        "titulo": "Frigobar",
        "descricao": "Frigobar",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["59-frigobar-1.jpeg", "59-frigobar-2.jpeg", "59-frigobar-3.jpeg"],
        "precoCerto": false,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 60,
        "titulo": "Árvore de Natal",
        "descricao": "Árvore de Natal com enfeites",
        "valor": 0.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": ["60-arvore-de-natal-1.jpeg", "60-arvore-de-natal-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Juliana",
        "entregue": false,
        "pago": false
    },
    {
        "id": 61,
        "titulo": "Jogos PS4",
        "descricao": "Jogos PS4",
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Jogos",
        "imagens": [],
        "subItems": [
            {
                "id": "61-2",
                "titulo": "Horizon Zero Dawn",
                "descricao": "Jogo Horizon Zero Dawn para PS4",
                "valor": 80.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-2-horizon-zero-dawn-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-3",
                "titulo": "Demon Slayer",
                "descricao": "Jogo Demon Slayer para PS4",
                "valor": 150.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-3-demon-slayer-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-4",
                "titulo": "Assassin's Creed Origins",
                "descricao": "Jogo Assassin's Creed Origins para PS4",
                "valor": 90.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-4-assassins-creed-origins-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-5",
                "titulo": "Spider-man",
                "descricao": "Jogo Spider-man para PS4",
                "valor": 120.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-5-spider-man-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-6",
                "titulo": "Crash Bandicoot N-Sane Trilogy",
                "descricao": "Jogo Crash Bandicoot N-Sane Trilogy para PS4",
                "valor": 120.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-6-crash-bandicoot-n-sane-trilogy-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-7",
                "titulo": "Red Dead Redemption 2",
                "descricao": "Jogo Red Dead Redemption 2 para PS4",
                "valor": 100.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-7-red-dead-redemption-2-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-8",
                "titulo": "Uncharted The Nathan Drake Collection",
                "descricao": "Jogo Uncharted The Nathan Drake Collection para PS4",
                "valor": 100.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-8-uncharted-the-nathan-drake-collection-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-9",
                "titulo": "Mortal Kombat XL",
                "descricao": "Jogo Mortal Kombat XL para PS4",
                "valor": 90.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-9-mortal-kombat-xl-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-10",
                "titulo": "South Park: A Fenda Que Abunda a Força",
                "descricao": "Jogo South Park: A Fenda Que Abunda a Força para PS4",
                "valor": 80.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-10-south-park-a-fenda-que-abunda-a-força-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-11",
                "titulo": "Fifa 17",
                "descricao": "Jogo Fifa 17 para PS4",
                "valor": 100.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-11-fifa-17-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            },
            {
                "id": "61-12",
                "titulo": "The Last Guardian",
                "descricao": "Jogo The Last Guardian para PS4",
                "valor": 100.00,
                "disponivel": true,
                "quantidade": 1,
                "dataEntrega": "Imediata",
                "estado": "Usado",
                "categoria": "Jogos",
                "imagens": ["61-12-the-last-guardian-1.png"],
                "reservadoPara": "",
                "entregue": false,
                "pago": false,
                "precoCerto": true
            }
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 62,
        "titulo": "Rack Estrela - Demolição e Amarelo",
        "descricao": "Rack Estrela - Demolição e Amarelo",
        "valor": 500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["62-estante-marrom-e-amarelo-1.jpeg", "62-estante-marrom-e-amarelo-2.jpeg", "62-estante-marrom-e-amarelo-3.jpeg", "62-estante-marrom-e-amarelo-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 63,
        "titulo": "Celular Poco X6 Pro 512gb Global 12gb Ram 5g Midnight Black",
        "descricao": "Celular Android Poco X6 Pro, com 512gb de memória interna, 12GB de RAM, e 5000mAh de bateria. Pouco uso, ficava em casa.",
        "valor": 1500.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["63-celular-android-poco-x6-pro-1.jpeg", "63-celular-android-poco-x6-pro-2.jpeg", "63-celular-android-poco-x6-pro-3.jpeg", "63-celular-android-poco-x6-pro-4.jpeg", "63-celular-android-poco-x6-pro-5.jpeg", "63-celular-android-poco-x6-pro-6.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Duda",
        "entregue": false,
        "pago": false
    },
    {
        "id": 64,
        "titulo": "Cabideiro",
        "descricao": "Cabideiro",
        "valor": 0.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["64-cabideiro-1.jpeg", "64-cabideiro-2.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Harley",
        "entregue": true,
        "pago": true
    },
    {
        "id": 65,
        "titulo": "Torradeira",
        "descricao": "Torradeira",
        "valor": 0.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Silvia",
        "entregue": false,
        "pago": false
    },
    {
        "id": 66,
        "titulo": "Tapete",
        "descricao": "Tapete",
        "valor": 150.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Sthu",
        "entregue": false,
        "pago": false
    },
    {
        "id": 67,
        "titulo": "Rede Wi-Fi Deco",
        "descricao": "Rede Wi-Fi Deco TP-Link.",
        "valor": 300.00,
        "disponivel": false,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["33-rede-wi-fi-deco-1.jpeg", "33-rede-wi-fi-deco-2.jpeg", "33-rede-wi-fi-deco-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Sthu",
        "entregue": false,
        "pago": false
    },
    {
        "id": 68,
        "titulo": "Alexa + 2 lampadas inteligentes",
        "descricao": "1 Alexas + 2 lampadas inteligentes",
        "valor": 300.00,
        "disponivel": false,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [],
        "precoCerto": true,
        "reservadoPara": "Harley",
        "entregue": true,
        "pago": true
    },
    {
        "id": 69,
        "titulo": "Nintendo DS Lite Preto",
        "descricao": "Nintendo DS Lite Preto + fonte + R4. Sempre usado com película. R4 é um cartão de memória que permite instalar diversos jogos. Já vai com vários jogos no R4.",
        "valor": 500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["69-nintendo-ds-1.jpeg", "69-nintendo-ds-2.jpeg", "69-nintendo-ds-3.jpeg", "69-nintendo-ds-4.jpeg", "69-nintendo-ds-5.jpeg", "69-nintendo-ds-6.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 70,
        "titulo": "Nintendo 64",
        "descricao": "Nintendo 64 original, com 2 controles originais + 2 jogos. Jogos: Mario Party e The Legend of Zelda: Ocarina of Time.",
        "valor": 500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["70-nintendo-64-1.jpeg", "70-nintendo-64-2.jpeg", "70-nintendo-64-3.jpeg", "70-nintendo-64-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 71,
        "titulo": "Master System Super Compact",
        "descricao": "Master System Super Compact Tec Toy original, sem fonte. Funciona com 4 pilhas. Com Sonic the Hedgehog na memória.",
        "valor": 500.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": ["71-master-system-1.jpeg", "71-master-system-2.jpeg", "71-master-system-3.jpeg", "71-master-system-4.jpeg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 72,
        "titulo": "TV Sony 32 polegadas",
        "descricao": "TV Sony KDL-32BX425. 32 polegadas. Não é smart. Com controle remoto.",
        "valor": 400.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["72-tv-sony-1.jpeg", "72-tv-sony-2.jpeg", "72-tv-sony-3.jpeg"],
        "precoCerto": true,
        "reservadoPara": "Marcelo Gorski",
        "entregue": true,
        "pago": true
    },
    {
        "id": 73,
        "titulo": "Fogão de Imbutir",
        "descricao": "Fogão de Imbutir 4 bocas com forno",
        "valor": 1300.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["73-fogao-imbutir-1.jpg", "73-fogao-imbutir-2.jpg", "73-fogao-imbutir-3.jpg", "73-fogao-imbutir-4.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 74,
        "titulo": "Depurador de Ar",
        "descricao": "Depurador de Ar Suggar",
        "valor": 130.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["74-depurador-ar-1.jpg", "74-depurador-ar-2.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 75,
        "titulo": "Armário de Limpeza",
        "descricao": "Armário de Limpeza",
        "valor": 0.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Fevereiro/2025",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["75-armario-limpeza-1.jpg", "75-armario-limpeza-2.jpg", "75-armario-limpeza-3.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 76,
        "titulo": "Aparador com Adega Bar",
        "descricao": "Aparador com Adega Bar estilo retrô 1 porta Lulu cor Branco",
        "valor": 150.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["76-bar-1.jpg", "76-bar-2.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 77,
        "titulo": "Cristaleira 2 Portas Retrô",
        "descricao": "Cristaleira 2 Portas Retrô",
        "valor": 250.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["77-cristaleira-1.jpg", "77-cristaleira-2.jpg", "77-cristaleira-3.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 79,
        "titulo": "Sapateira",
        "descricao": "Sapateira",
        "valor": 100.00,
        "disponivel": true,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Móveis",
        "imagens": ["79-sapateira-1.jpg", "79-sapateira-2.jpg", "79-sapateira-3.jpg", "79-sapateira-4.jpg", "79-sapateira-5.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 80,
        "titulo": "Quadro Deadpool",
        "descricao": "Quadro Deadpool",
        "valor": 50.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Decoração",
        "imagens": ["80-quadro-deadpool-1.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 81,
        "titulo": "DVDs",
        "descricao": "DVDs",
        "valor": 0.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": ["81-DVDs-1.jpg"],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 82,
        "titulo": "Guitar Hero: Warriors Of Rock Bundle Guitarra Ps3",
        "descricao": "Guitarra + Jogo Guitar Hero Warriors of Rock para PS3",
        "valor": 800.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": [
            "82-guitar-hero-warriors-rock-1.jpeg",
            "82-guitar-hero-warriors-rock-2.jpeg",
            "82-guitar-hero-warriors-rock-3.jpeg",
            "82-guitar-hero-warriors-rock-4.jpeg",
            "82-guitar-hero-warriors-rock-5.jpeg",
            "82-guitar-hero-warriors-rock-6.jpeg",
            "82-guitar-hero-warriors-rock-7.jpeg",
            "82-guitar-hero-warriors-rock-8.jpeg",
            "82-guitar-hero-warriors-rock-9.jpeg"
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 83,
        "titulo": "Controle Pro Nintendo Switch",
        "descricao": "Controle Pro Nintendo Switch",
        "valor": 250.00,
        "disponivel": true,
        "quantidade": 2,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": [
            "83-controle-pro-switch-1.jpeg",
            "83-controle-pro-switch-2.jpeg",
            "83-controle-pro-switch-3.jpeg"
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 84,
        "titulo": "Controle Xbox 360 PC",
        "descricao": "Controle Xbox 360 para PC com fio",
        "valor": 80.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": [
            "84-controle-xbox-360-1.jpeg",
            "84-controle-xbox-360-2.jpeg",
            "84-controle-xbox-360-3.jpeg"
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 85,
        "titulo": "Meta Quest 1 + Acessórios",
        "descricao": "Meta Quest 1 + Acessórios. Tem 2 dead pixels na tela. Sempre usado com capa de silicone. Com acessóios: adaptador para beat saber, Strap com regulagem, lentes extras. almofadas para o rosto e porta bateria extra.",
        "valor": 800.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Videogames",
        "imagens": [
            "85-meta-quest-1.jpeg",
            "85-meta-quest-2.jpeg",
            "85-meta-quest-3.jpeg",
            "85-meta-quest-4.jpeg",
            "85-meta-quest-5.jpeg",
            "85-meta-quest-6.jpeg",
            "85-meta-quest-7.jpeg"
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 86,
        "titulo": "Suporte Notebook",
        "descricao": "Suporte Notebook",
        "valor": 0.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrônicos",
        "imagens": [
            "86-suporte-notebook-1.jpeg",
            "86-suporte-notebook-2.jpeg",
            "86-suporte-notebook-3.jpeg"
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    },
    {
        "id": 87,
        "titulo": "Máquina de Tosa Profissional",
        "descricao": "Máquina De Tosa Profissional Wahl Speed Km2 127v",
        "valor": 400.00,
        "disponivel": true,
        "quantidade": 1,
        "dataEntrega": "Imediata",
        "estado": "Usado",
        "categoria": "Eletrodomésticos",
        "imagens": [
            "87-maquina-tosadora-1.jpeg",
            "87-maquina-tosadora-2.jpeg",
            "87-maquina-tosadora-3.jpeg",
            "87-maquina-tosadora-4.jpeg",
            "87-maquina-tosadora-5.jpeg",
            "87-maquina-tosadora-6.jpeg",
            "87-maquina-tosadora-7.jpeg"
        ],
        "precoCerto": true,
        "reservadoPara": "",
        "entregue": false,
        "pago": false
    }
];
